module.exports = {
  LEAGUES: [
    "Eng Premier",
    // "Spanish Division 1",
    // "Italian Division 1",
    // "German Division 1",
    // "French Division 1",
  ],

  YEARS: {
    "Eng Premier": ["2022-2023", "2023-2024", "2024-2025"],
    "Spanish Division 1": ["2022-2023", "2023-2024", "2024-2025"],
    "Italian Division 1": ["2022-2023", "2023-2024", "2024-2025"],
    "German Division 1": ["2022-2023", "2023-2024", "2024-2025"],
    "French Division 1": ["2022-2023", "2023-2024", "2024-2025"],
  },

  PAGES: {
    "Eng Premier": "https://bet.hkjc.com/en/football/hdc?tournid=50000051",
    "Spanish Division 1": "https://bet.hkjc.com/en/football/hdc?tournid=50000100",
    "Italian Division 1": "https://bet.hkjc.com/en/football/hdc?tournid=50000069",
    "German Division 1": "https://bet.hkjc.com/en/football/hdc?tournid=50000063",
    "French Division 1": "https://bet.hkjc.com/en/football/hdc?tournid=50000058",
  },

  TEAMS: {
    "Eng Premier": {
      "2024-2025": {
        Arsenal: "Arsenal(阿仙奴)",
        "Aston Villa": "Aston Villa(阿士東維拉)",
        Bournemouth: "Bournemouth(般尼茅夫)",
        Brentford: "Brentford(賓福特)",
        Brighton: "Brighton(白禮頓)",
        Chelsea: "Chelsea(車路士)",
        "Crystal Palace": "Crystal Palace(水晶宮)",
        Everton: "Everton(愛華頓)",
        Fulham: "Fulham(富咸)",
        Ipswich: "Ipswich(葉士域治)",
        Leicester: "Leicester(李斯特城)",
        Liverpool: "Liverpool(利物浦)",
        "Manchester City": "Manchester City(曼城)",
        "Manchester Utd": "Manchester Utd(曼聯)",
        Newcastle: "Newcastle(紐卡素)",
        Nottingham: "Nottingham Forest(諾定咸森林)",
        Southampton: "Southampton(修咸頓)",
        Tottenham: "Tottenham(熱刺)",
        "West Ham": "West Ham(韋斯咸)",
        Wolves: "Wolves(狼隊)",
      },

      "2023-2024": {
        Arsenal: "Arsenal(阿仙奴)",
        "Aston Villa": "Aston Villa(阿士東維拉)",
        Bournemouth: "Bournemouth(般尼茅夫)",
        Brentford: "Brentford(賓福特)",
        Brighton: "Brighton(白禮頓)",
        Chelsea: "Chelsea(車路士)",
        "Crystal Palace": "Crystal Palace(水晶宮)",
        Everton: "Everton(愛華頓)",
        Fulham: "Fulham(富咸)",
        Liverpool: "Liverpool(利物浦)",
        "Manchester City": "Manchester City(曼城)",
        "Manchester Utd": "Manchester Utd(曼聯)",
        Newcastle: "Newcastle(紐卡素)",
        Nottingham: "Nottingham Forest(諾定咸森林)",
        Tottenham: "Tottenham(熱刺)",
        "West Ham": "West Ham(韋斯咸)",
        Wolves: "Wolves(狼隊)",

        // 2023 teams
        Burnley: "Burnley(般尼)",
        Luton: "Luton(盧頓)",
        "Sheffield Utd": "Sheff Utd(錫菲聯)",
      },

      "2022-2023": {
        Arsenal: "Arsenal(阿仙奴)",
        "Aston Villa": "Aston Villa(阿士東維拉)",
        Bournemouth: "Bournemouth(般尼茅夫)",
        Brentford: "Brentford(賓福特)",
        Brighton: "Brighton(白禮頓)",
        Chelsea: "Chelsea(車路士)",
        "Crystal Palace": "Crystal Palace(水晶宮)",
        Everton: "Everton(愛華頓)",
        Fulham: "Fulham(富咸)",
        Liverpool: "Liverpool(利物浦)",
        "Manchester City": "Manchester City(曼城)",
        "Manchester Utd": "Manchester Utd(曼聯)",
        Newcastle: "Newcastle(紐卡素)",
        Nottingham: "Nottingham Forest(諾定咸森林)",
        Tottenham: "Tottenham(熱刺)",
        "West Ham": "West Ham(韋斯咸)",
        Wolves: "Wolves(狼隊)",

        // 2022 teams
        Leicester: "Leicester(李斯特城)",
        Southampton: "Southampton(修咸頓)",
        Leeds: "Leeds(列斯聯)",
      },

      Others: {
        Burnley: "Burnley(般尼)",
        Watford: "Watford(屈福特)",
        Norwich: "Norwich(諾域治)",
        "West Brom": "West Brom(西布朗)",
      },
    },

    "Spanish Division 1": {
      "2024-2025": {
        Alaves: "Alaves(艾拉維斯)",
        "Ath Bilbao": "Bilbao(畢爾包)",
        "Atl. Madrid": "Atletico Madrid(馬德里體育會)",
        Barcelona: "Barcelona(巴塞隆拿)",
        Betis: "Betis(貝迪斯)",
        "Celta Vigo": "Celta Vigo(切爾達)",
        Espanyol: "Espanyol(愛斯賓奴)",
        Getafe: "Getafe(基達菲)",
        Girona: "Girona(基羅納)",
        "Las Palmas": "Las Palmas(拉斯彭馬斯)",
        Leganes: "Leganes(雷加利斯)",
        Mallorca: "Mallorca(馬略卡)",
        Osasuna: "Osasuna(奧沙辛拿)",
        "Rayo Vallecano": "Vallecano(華歷簡奴)",
        "Real Madrid": "Real Madrid(皇家馬德里)",
        "Real Sociedad": "Real Sociedad(皇家蘇斯達)",
        Sevilla: "Sevilla(西維爾)",
        Valencia: "Valencia(華倫西亞)",
        Valladolid: "Valladolid(華拉度列)",
        Villarreal: "Villarreal(維拉利爾)",
      },

      "2023-2024": {
        Alaves: "Alaves(艾拉維斯)",
        Almeria: "Almeria(艾美利亞)",
        "Ath Bilbao": "Bilbao(畢爾包)",
        "Atl. Madrid": "Atletico Madrid(馬德里體育會)",
        Barcelona: "Barcelona(巴塞隆拿)",
        Betis: "Betis(貝迪斯)",
        "Cadiz CF": "Cadiz(卡迪斯)",
        "Celta Vigo": "Celta Vigo(切爾達)",
        Espanyol: "Espanyol(愛斯賓奴)",
        Getafe: "Getafe(基達菲)",
        Girona: "Girona(基羅納)",
        "Granada CF": "CF Granada(CF格蘭納達)",
        "Las Palmas": "Las Palmas(拉斯彭馬斯)",
        Mallorca: "Mallorca(馬略卡)",
        Osasuna: "Osasuna(奧沙辛拿)",
        "Rayo Vallecano": "Vallecano(華歷簡奴)",
        "Real Madrid": "Real Madrid(皇家馬德里)",
        "Real Sociedad": "Real Sociedad(皇家蘇斯達)",
        Sevilla: "Sevilla(西維爾)",
        Valencia: "Valencia(華倫西亞)",
        Villarreal: "Villarreal(維拉利爾)",
      },

      "2022-2023": {
        Almeria: "Almeria(艾美利亞)",
        "Ath Bilbao": "Bilbao(畢爾包)",
        "Atl. Madrid": "Atletico Madrid(馬德里體育會)",
        Barcelona: "Barcelona(巴塞隆拿)",
        Betis: "Betis(貝迪斯)",
        "Cadiz CF": "Cadiz(卡迪斯)",
        "Celta Vigo": "Celta Vigo(切爾達)",
        Elche: "CF Elche(艾爾切)",
        Espanyol: "Espanyol(愛斯賓奴)",
        Getafe: "Getafe(基達菲)",
        Girona: "Girona(基羅納)",
        Mallorca: "Mallorca(馬略卡)",
        Osasuna: "Osasuna(奧沙辛拿)",
        "Rayo Vallecano": "Vallecano(華歷簡奴)",
        "Real Madrid": "Real Madrid(皇家馬德里)",
        "Real Sociedad": "Real Sociedad(皇家蘇斯達)",
        Sevilla: "Sevilla(西維爾)",
        Valencia: "Valencia(華倫西亞)",
        Villarreal: "Villarreal(維拉利爾)",
        Valladolid: "Valladolid(華拉度列)",
      },

      others: {
        Eibar: "Eibar(伊巴)",
        Huesca: "Huesca(侯爾斯卡)",
        Levante: "Levante(利雲特)",
        Malaga: "Malaga(馬拉加)",
      },
    },

    "Italian Division 1": {
      "2024-2025": {
        Atalanta: "Atalanta(阿特蘭大)",
        Bologna: "Bologna(博洛尼亞)",
        Cagliari: "Cagliari(卡利亞里)",
        Como: "Como(科木)",
        Empoli: "Empoli(安玻里)",
        Fiorentina: "Fiorentina(費倫天拿)",
        Genoa: "Genoa(熱拿亞)",
        Inter: "Inter Milan(國際米蘭)",
        Juventus: "Juventus(祖雲達斯)",
        Lazio: "Lazio(拉素)",
        Lecce: "Lecce(萊切)",
        Monza: "Monza(蒙沙)",
        Milan: "AC Milan(AC米蘭)",
        Napoli: "Napoli(拿玻里)",
        Parma: "Parma(帕爾馬)",
        Roma: "Roma(羅馬)",
        Torino: "Torino(拖連奴)",
        Udinese: "Udinese(烏甸尼斯)",
        Venezia: "Venezia(威尼斯)",
        Verona: "Verona(維羅納)",
      },

      "2023-2024": {
        Atalanta: "Atalanta(阿特蘭大)",
        Bologna: "Bologna(博洛尼亞)",
        Cagliari: "Cagliari(卡利亞里)",
        Empoli: "Empoli(安玻里)",
        Fiorentina: "Fiorentina(費倫天拿)",
        Frosinone: "Frosinone(費辛龍尼)",
        Genoa: "Genoa(熱那亞)",
        Inter: "Inter Milan(國際米蘭)",
        Juventus: "Juventus(祖雲達斯)",
        Lazio: "Lazio(拉素)",
        Lecce: "Lecce(萊切)",
        Monza: "Monza(蒙沙)",
        Milan: "AC Milan(AC米蘭)",
        Napoli: "Napoli(拿玻里)",
        Roma: "Roma(羅馬)",
        Salernitana: "Salernitana(沙蘭力坦拿)",
        Sassuolo: "Sassuolo(薩斯索羅)",
        Torino: "Torino(拖連奴)",
        Udinese: "Udinese(烏甸尼斯)",
        Verona: "Verona(維羅納)",
      },

      "2022-2023": {
        Atalanta: "Atalanta(阿特蘭大)",
        Bologna: "Bologna(博洛尼亞)",
        Cremonese: "Cremonese(克雷莫納)",
        Empoli: "Empoli(安玻里)",
        Fiorentina: "Fiorentina(費倫天拿)",
        Inter: "Inter Milan(國際米蘭)",
        Juventus: "Juventus(祖雲達斯)",
        Lazio: "Lazio(拉素)",
        Lecce: "Lecce(萊切)",
        Monza: "Monza(蒙沙)",
        Milan: "AC Milan(AC米蘭)",
        Napoli: "Napoli(拿玻里)",
        Roma: "Roma(羅馬)",
        Salernitana: "Salernitana(沙蘭力坦拿)",
        Sampdoria: "Sampdoria(森多利亞)",
        Spezia: "Spezia(史柏斯亞)",
        Sassuolo: "Sassuolo(薩斯索羅)",
        Torino: "Torino(拖連奴)",
        Udinese: "Udinese(烏甸尼斯)",
        Verona: "Verona(維羅納)",
      },
    },

    "German Division 1": {
      "2024-2025": {
        Augsburg: "Augsburg(奧格斯堡)",
        Bayern: "Bayern Munich(拜仁慕尼黑)",
        Bochum: "Bochum(波琴)",
        Dortmund: "Dortmund(多蒙特)",
        Darmstadt: "Darmstadt(達斯泰特)",
        Frankfurt: "Frankfurt(法蘭克福)",
        Freiburg: "Freiburg(弗賴堡)",
        Heidenheim: "Heidenheim(海登咸)",
        Hoffenheim: "Hoffenheim(賀芬咸)",
        Cologne: "Cologne(科隆)",
        Leipzig: "RB Leipzig(RB萊比錫)",
        Leverkusen: "Leverkusen(利華古遜)",
        Mainz: "Mainz(緬恩斯)",
        Monchengladbach: "Monchengladbach(慕遜加柏)",
        Stuttgart: "Stuttgart(史特加)",
        "Union Berlin": "Union Berlin(柏林聯)",
        "Werder Bremen": "Werder Bremen(雲達不來梅)",
        Wolfsburg: "Wolfsburg(禾夫斯堡)",
      },

      "2023-2024": {
        Augsburg: "Augsburg(奧格斯堡)",
        Bayern: "Bayern Munich(拜仁慕尼黑)",
        Bochum: "Bochum(波琴)",
        Dortmund: "Dortmund(多蒙特)",
        Darmstadt: "Darmstadt(達斯泰特)",
        Frankfurt: "Frankfurt(法蘭克福)",
        Freiburg: "Freiburg(弗賴堡)",
        Heidenheim: "Heidenheim(海登咸)",
        Hoffenheim: "Hoffenheim(賀芬咸)",
        Köln: "Cologne(科隆)",
        Leipzig: "RB Leipzig(RB萊比錫)",
        Leverkusen: "Leverkusen(利華古遜)",
        Mainz: "Mainz(緬恩斯)",
        Monchengladbach: "Monchengladbach(慕遜加柏)",
        Stuttgart: "Stuttgart(史特加)",
        "Union Berlin": "Union Berlin(柏林聯)",
        "Werder Bremen": "Werder Bremen(雲達不來梅)",
        Wolfsburg: "Wolfsburg(禾夫斯堡)",
      },

      "2022-2023": {
        Augsburg: "Augsburg(奧格斯堡)",
        Bayern: "Bayern Munich(拜仁慕尼黑)",
        Bochum: "Bochum(波琴)",
        Dortmund: "Dortmund(多蒙特)",
        Frankfurt: "Frankfurt(法蘭克福)",
        Freiburg: "Freiburg(弗賴堡)",
        Hoffenheim: "Hoffenheim(賀芬咸)",
        Köln: "Cologne(科隆)",
        Leipzig: "RB Leipzig(RB萊比錫)",
        Leverkusen: "Leverkusen(利華古遜)",
        Mainz: "Mainz(緬恩斯)",
        Monchengladbach: "Monchengladbach(慕遜加柏)",
        Stuttgart: "Stuttgart(史特加)",
        "Union Berlin": "Union Berlin(柏林聯)",
        "Werder Bremen": "Werder Bremen(雲達不來梅)",
        Wolfsburg: "Wolfsburg(禾夫斯堡)",
        Schalke: "Schalke 04(史浩克04)",
        Hertha: "Hertha Berlin(哈化柏林)",
      },
    },

    "French Division 1": {
      "2024-2025": {
        Angers: "Angers SCO(昂熱)",
        Auxerre: "Auxerre(歐塞爾)",
        Brest: "Brest(比斯特)",
        "Le Havre": "Le Havre(勒哈弗爾)",
        Lens: "Lens(朗斯)",
        Lille: "Lille(里爾)",
        Lyon: "Lyon(里昂)",
        Marseille: "Marseille(馬賽)",
        Monaco: "Monaco(摩納哥)",
        Montpellier: "Montpellier(蒙彼利埃)",
        Nantes: "Nantes(南特)",
        Nice: "Nice(尼斯)",
        PSG: "Paris Saint Germain(巴黎聖日耳門)",
        Reims: "Reims(蘭斯)",
        Rennes: "Rennes(雷恩)",
        Strasbourg: "Strasbourg(斯特拉斯堡)",
        "St Etienne": "St. Etienne(聖伊天)",
      },

      "2023-2024": {
        Brest: "Brest(比斯特)",
        Clermont: "Clermont(克萊蒙特)",
        Lens: "Lens(朗斯)",
        Lille: "Lille(里爾)",
        Lorient: "Lorient(羅連安特)",
        Lyon: "Lyon(里昂)",
        Marseille: "Marseille(馬賽)",
        Metz: "Metz(梅斯)",
        Monaco: "Monaco(摩納哥)",
        Montpellier: "Montpellier(蒙彼利埃)",
        Nantes: "Nantes(南特)",
        Nice: "Nice(尼斯)",
        PSG: "Paris Saint Germain(巴黎聖日耳門)",
        Reims: "Reims(蘭斯)",
        Rennes: "Rennes(雷恩)",
        Strasbourg: "Strasbourg(斯特拉斯堡)",
        Toulouse: "Toulouse(圖盧茲)",
        "Le Havre": "Le Havre(勒哈弗爾)",
      },

      "2022-2023": {
        Angers: "Angers SCO(昂熱)",
        Auxerre: "Auxerre(歐塞爾)",
        Brest: "Brest(比斯特)",
        Clermont: "Clermont(克萊蒙特)",
        Lens: "Lens(朗斯)",
        Lille: "Lille(里爾)",
        Lorient: "Lorient(羅連安特)",
        Lyon: "Lyon(里昂)",
        Marseille: "Marseille(馬賽)",
        Monaco: "Monaco(摩納哥)",
        Montpellier: "Montpellier(蒙彼利埃)",
        Nantes: "Nantes(南特)",
        Nice: "Nice(尼斯)",
        PSG: "Paris Saint Germain(巴黎聖日耳門)",
        Reims: "Reims(蘭斯)",
        Rennes: "Rennes(雷恩)",
        Strasbourg: "Strasbourg(斯特拉斯堡)",
        Toulouse: "Toulouse(圖盧茲)",
        Troyes: "Troyes(特魯瓦)",
        Ajaccio: "Ajaccio(阿些斯奧)",
      },
    },
  }
};